{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyPbyYioGUz+Lx7fbMWbH7hw",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/Cauribeiro14/prova/blob/main/prova.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "qtllZltYTVcJ",
        "outputId": "a5fbcd87-3037-4277-aeaf-93919a058b20"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Exercicio 1\n",
            "Exercicio 3\n",
            "Exercicio 4\n",
            "Sair 6\n"
          ]
        }
      ],
      "source": [
        "#Avaliação1\n",
        "#Aluno: Claudiane Ribeiro / Muller Araujo do Vale\n",
        "\n",
        "def problema1():\n",
        "  #Avaliação1\n",
        "  \"\"\"1 - O custo ao consumidor de um carro novo é a soma do custo de fábrica\n",
        "com a porcentagem do distribuidor e dos impostos (aplicados ao custo de\n",
        "fábrica).\n",
        "Supondo que a porcentagem do distribuidor seja de 8% do preço de fábrica\n",
        "e os impostos de 20% do preço de fábrica, fazer um programa em Python\n",
        "para ler o custo de fábrica de um carro e imprimir, o preço de fábrica, o valor do imposto, o valor da porcentagem do distribuidor custo e ao consumidor. Usar funções. No inicio do código insira o comentário\"\"\"\n",
        "\n",
        "  valorcarro = float(input(\"digite o valor do carro\"))\n",
        "\n",
        "  valorfabrica = valorcarro * 0.8\n",
        "\n",
        "  valorimposto = valorfabrica * 0.20\n",
        "\n",
        "  print(\"Valor de Fabrica {}\".format(valorfabrica))\n",
        "  print(\"Valor de imposto {}\".format(valorimposto))\n",
        "  print(\"o valor da porcentagem do distribuidor custo {}\".format())\n",
        "  print(\"o valor da comumidor\")\n",
        "\n",
        "def problema3():\n",
        "  #Avaliação1\n",
        "  \"\"\"3 - Elabore um programa em Python que leia as duas notas de prova (P1 e\n",
        "P2) e duas notas de trabalho (T1 e T2) e posteriormente exiba a mensagem\n",
        "‘Aprovado’ ou ‘Não aprovado’ dependendo dos valores obtidos, conforme\n",
        "as regras de cálculo definidas a seguir:\n",
        "· Média de provas: MP = (P1 + P2)/2\n",
        "· Média de trabalhos: MT = (T1 + T2)/2\n",
        "· Média final: MF = 0,6MP + 0,4MT\n",
        "· Situação:Se MF ≥ 6,0 → aprovado\n",
        "· Se MF < 6,0 → não aprovado\n",
        "· Usar funções.\n",
        "· No inicio do código insira o comentário”\"\"\"\n",
        "\n",
        "  P1 = float(input(\"Digite o valor da prova P1\\n\"))\n",
        "  P2 = float(input(\"Digite o valor da prova P2\\n\"))\n",
        "  T1 = float(input(\"Digite o valor do trabalho T1\\n\"))\n",
        "  T2 = float(input(\"Digite o valor do trabalho T2\\n\"))\n",
        "\n",
        "  MP = (P1 + P2)/2 #1.65\n",
        "\n",
        "  MT = (T1 + T2)/2 #3.85\n",
        "\n",
        "  MF = (0.6 * MP) + (0.4 * MT) #(0.6 * 1.65) + (0.4 * 3.85)\n",
        "                               #0,99 + 1,54\n",
        "\n",
        "  print(\"Sua nota é: {}\".format(MF) )\n",
        "\n",
        "  if MF < 6:\n",
        "    print(\"Não Aprovado\")\n",
        "  else:\n",
        "    print(\"Aprovado\")\n",
        "\n",
        "def menuproblema():\n",
        "  print(\"1 - Depositar\")\n",
        "  print(\"2 - Sacar\")\n",
        "  print(\"3 - Consultar Saldo\")\n",
        "  print(\"4 - Sair\")\n",
        "\n",
        "  opcao = input(\"Digite um das opcao\")\n",
        "\n",
        "  return opcao\n",
        "\n",
        "def Sacar():\n",
        "  sacar =  float(input(\"Digite seu valor de saque!\"))\n",
        "\n",
        "  return sacar\n",
        "\n",
        "def Depositar():\n",
        "  deposito = float(input(\"Digite seu deposito!\"))\n",
        "\n",
        "  return deposito\n",
        "\n",
        "def ConsultarSaldo(saldo):\n",
        "  print(\"seu saldo e de {}\".format(saldo))\n",
        "\n",
        "def problema4():\n",
        "  #Avaliação1\n",
        "  \"\"\"4 - Faça um programa em Python que simula as operações de um banco. O\n",
        "programa deve apresentar um menu com as seguintes opções:\n",
        "1. Depositar (O programa deve pedir o valor a ser depositado e somá-lo\n",
        "ao saldo)\n",
        "2. Sacar (O programa deve pedir o valor a ser sacado e subtrair do saldo, desde que o valor seja menor ou igual ao saldo disponível)\n",
        "3. Consultar Saldo (O programa deve exibir o saldo atual)\n",
        "4. Sair (O programa termina). No inicio do código insira o comentário “..=”\n",
        "“Avaliação1 ” “=..”\n",
        "O programa deve manter um saldo inicial de R$ 200.00 e permitir ao usuário realizar operações até que ele escolha a opção \"Sair\". Usar funções.\n",
        "  saldo = 200.00\"\"\"\n",
        "\n",
        "  while True:\n",
        "    opcao = menuproblema()\n",
        "\n",
        "    if opcao == \"1\":\n",
        "      saldo = saldo + Depositar()\n",
        "    elif opcao == \"2\":\n",
        "      saldo = saldo - Sacar()\n",
        "    elif opcao == \"3\":\n",
        "      ConsultarSaldo(saldo)\n",
        "    elif opcao == \"4\":\n",
        "      break\n",
        "    else:\n",
        "      print(\"opção nao encontrada!\")\n",
        "\n",
        "\n",
        "\n",
        "def menu():\n",
        "\n",
        "  opcao = \"\"\n",
        "\n",
        "  while True:\n",
        "    print(\"Exercicio 1\")\n",
        "    print(\"Exercicio 3\")\n",
        "    print(\"Exercicio 4\")\n",
        "    print(\"Sair 6\")\n",
        "    opcao = input(\"Digite sua opção\")\n",
        "\n",
        "    if opcao == \"1\":\n",
        "        problema1()\n",
        "    elif opcao == \"3\":\n",
        "      problema3()\n",
        "    elif opcao == \"4\":\n",
        "      problema4()\n",
        "    elif opcao == \"6\":\n",
        "      break\n",
        "    else:\n",
        "      print(\"não existe esse opção!\")\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "def main():\n",
        "  menu()\n",
        "\n",
        "\n",
        "if __name__ == '__main__':\n",
        "  main()"
      ]
    }
  ]
}